Collection.Nodes
    .permit(['insert'])
    .ifLoggedIn()
    .onlyProps([
        'title',
        'content',
        'language',
        'color',
        'from',
        'location'
    ])
    .apply();
